// <auto-generated />
namespace BanVeDiTourDuLich.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ChangenameChiTietandTinhNang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangenameChiTietandTinhNang));
        
        string IMigrationMetadata.Id
        {
            get { return "202010260342036_Change name ChiTiet and TinhNang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
